export enum E_Routes {
  users = '/users',
  admins = '/admins',
  articles = '/articles',
  tags = '/tags',
  viewArticle = '/articles/:id',
  updateArticle = '/articles/:id/update',
  createArticle = '/articles/create',
  createTag = '/tags/create',
  updateTag = '/tags/:id/update',
  viewTag = '/tags/:id',
  viewAdmin = '/admins/:id',
  createAdmin = '/admins/create',
  updateAdminEmail = '/admins/:id/update',
  updateAdminPassword = '/admins/:id/updatePassword',
}
